[WIP] closes #2404 Disable "Move to bottom" button on companion windows when canvas height is less than 300px
ProjectMirador/mirador pull request #2541
Opened 2019-04-17 13:12 UTC by glefi

2019-04-19 21:18 UTC, jkeck submitted a review, later dismissed
Thanks for tackling this @glefi.  I'm not able to get the desired result in the Netlify deploy.  If I'm understanding the goal of #2404 correctly, then I should not be able to get into this scenario:

<img width="639" alt="Short Window" src="https://user-images.githubusercontent.com/96776/56444446-a6464c80-62ad-11e9-9369-2bdc50f3babb.png">

The window itself here is shorter than 200px so the canvas area is definitely smaller than that, so I believe this button should be either disabled or not present (but I can move the companion window from that height).

2019-04-23 09:32 UTC, glefi commented
Thanks for your comment @jkeck The latest commit fixes the disabling of the button, in case the canvas's size is lower than 300px.

2019-05-04 08:59 UTC, mejackreed requested changes
This is working nicely when the companion window is on the right side. I did however notice a crash when the companion window is on the bottom and < 300 px.

`Uncaught Invariant Violation: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.`

2019-05-06 10:15 UTC, glefi commented
@mejackreed thanks for pointing that out. the latest commit should fix the problem.

2019-05-06 18:53 UTC, jkeck submitted a review, later dismissed

2019-05-06 18:53 UTC, jkeck commented on src/containers/CompanionWindow.js
> +  const showMoveToBottom = !window.height || window.height > 300 || companionWindow.position !== 'right';
@glefi I believe the desired behavior here is to `disable` the button, not necessarily remove it all-together.  I think this should be a value that would be passed to the appropriate `MiradorMenuButton` component as the `disabled` prop (which would also indicate a potential name/logic change).

2026-07-09 15:52 UTC, marlo-longley commented
Stale now, but a good reference for https://github.com/ProjectMirador/mirador/issues/2404 in 2026. Thanks for the work here.

2026-07-09 15:52 UTC, closed without merging