Get multi-sequences to work for v3 ranges/seqs
ProjectMirador/mirador pull request #3333
Opened 2020-11-02 19:50 UTC by MImranAsghar

- Update sequences and canvases selectors to get multi-sequences to work for v3 top-level ranges with behavior sequence
- Add integration test for v3 multi sequences

2020-11-03 18:23 UTC, mejackreed commented
Thanks for moving this forward @MImranAsghar . I'm seeing some issues here which seems related. Can you investigate? https://deploy-preview-3333--mirador-dev.netlify.app/__tests__/integration/mirador/toc.html

2020-11-03 19:00 UTC, MImranAsghar commented
Thanks Jack. Yes, looking into it.

2020-11-10 18:24 UTC, MImranAsghar commented
Hi @mejackreed , i have added some more changes. I think for the tests `  ● how plugins relate to state › plugin can catch core action in its reducer
` is the one that is timing out. any suggestions of why this could be?

2020-11-10 21:23 UTC, MImranAsghar commented
when running these tests on mirador multiple times, some tests are giving timeout in a particular run but when I run the tests again the timeout disappears. Is it okay if those tests fail(timeout) in a pull request in that case?

2020-11-17 16:03 UTC, mejackreed requested changes
Thanks for continuing to move this forward @MImranAsghar . However, I'm seeing some issues with previous working content: `https://iiif.bodleian.ox.ac.uk/iiif/manifest/e32a277e-91e2-4a6d-8ba6-cc4bad230410.json` 

It would also be helpful I think to either (or both) add some additional unit tests in the modified selectors to better codify the changes that are happening. I'm still not fully clear on what the modeling changes are intended to represent.

2020-11-17 16:03 UTC, mejackreed commented on src/state/selectors/sequences.js
> +       && !manifestSequences[0].id) {
Can you say more about the case where an id would not be present?

2020-11-17 16:50 UTC, MImranAsghar commented on src/state/selectors/canvases.js
> +    if (!window.canvasId && (typeof sequence.getCanvasByIndex == 'function')) {
Hi Jack, this is for when the sequence represents a 'Range' manifesto object here which does not provide the 'getCanvasById' or 'getCanvases' function. 'Range' manifesto object has 'items' where it lists all the canvases.

2020-11-17 16:52 UTC, MImranAsghar commented on src/containers/WindowSideBarCanvasPanel.js
> +    '& .MuiSelect-icon': {
Hi Jack, this is for constaining the size of the select dropdown so it does not extend beyond the sidebar panel when there is a long sequence label.. the reasoning for setting background color to white was to make sure that the 'Arrow icon' in the select bar and the label don't overlap.

2020-11-23 19:45 UTC, MImranAsghar commented on src/state/selectors/sequences.js
> +    }
Hi @mejackreed , I made a pull request to 'get' canvases in the iiif manifesto library as well so this specific change won't be needed in future and i will remove it later after that pull request gets accepted. The manifesto pull request is here https://github.com/IIIF-Commons/manifesto/pull/79. Also I was wondering if you got a chance to get feedback from the designer on whether the additional sequence (which includes all manifest canvases) can be created and displayed (even if its not listed as seqs). I can make the changes accordingly after feedback from the designer.

2026-07-14 17:52 UTC, marlo-longley commented
Closing this PR as it is pretty stale now and depends on some outside work in Manifesto (that PR is tracked in the ticket #2949)
Leaving #2949 open as it tracks the underlying need. Can reference this work in a new PR.

2026-07-14 17:52 UTC, closed without merging