fix:mirador_crash
ProjectMirador/mirador pull request #3927
Opened 2024-07-30 11:12 UTC by fstoe

I found out that adding something through the add button in the catalog view which is json but not a manifest makes the viewer crash.
steps to reproduce:
- Open Mirador
- Add Resource with example url:  https://iiif.io/api/presentation/2/context.json
- Open legit resource

2024-08-02 09:07 UTC, lutzhelm commented
Hi @fstoe, could you add a test case for that patch? `createManifestoInstance` itself is not exported, but `getManifestoInstance` calls it directly, so this would be a good place to add a test:

https://github.com/ProjectMirador/mirador/blob/master/__tests__/src/selectors/manifests.test.js#L56-L68

Something like
``` javascript
it('does not crash if json is not a manifest', () => {
  const state = { manifests: { x: { json: {} } } };
  const received = getManifestoInstance(state, { manifestId: 'x' });
  expect(received).toBe(undefined);
});
```

2024-08-05 11:11 UTC, fstoe commented
Hey @lutzhelm, 
thanks for the comment. I just added a small test case

2025-01-15 10:25 UTC, lutzhelm requested changes

2025-01-15 10:25 UTC, lutzhelm commented on __tests__/src/selectors/manifests.test.js
>    it('is cached based off of input props', () => {
This test has been removed on `main`. I don't know the reason, but it's the cause of the current merge conflict. Could you resolve this conflict e.g. by merging `main` into this branch? Just be sure that the test case actually stays removed.

2025-01-15 10:25 UTC, lutzhelm commented on __tests__/src/selectors/manifests.test.js
> +  it('creates a manifesto collection instance and patches getSequences', () => {
Not important, but could you insert an empty line above? The eslint rules actually don't enforce that but it would be more consistent. Thanks!

2025-01-16 11:10 UTC, fstoe commented on __tests__/src/selectors/manifests.test.js
>    it('is cached based off of input props', () => {
Done :)

2025-01-28 14:44 UTC, lutzhelm submitted a review, later dismissed

2025-01-28 15:57 UTC, lutzhelm commented on src/containers/ManifestListItem.js
> +    error: manifest.error || !manifesto,
I should have noticed this earlier: This change results in a list of errors in the catalog list for every manifest that is configured in the `catalog` settings but not in `windows`. While you can "Try again" successfully, this should be fixed. It's probably sufficient to change this line to
```
    error: manifest.error || (!manifesto && !!manifest.json),
```
Manifests that have not been used in windows before don't have a manifesto instance up until this point, and at the moment the component is initially rendered, `isFetching` is not yet true, so the same check that is used for `ready` should be used here additionally.

2025-01-28 15:59 UTC, lutzhelm commented on src/containers/ManifestListItem.js
> +    error: manifest.error || !manifesto,
I'm also thinking about how to test this automatically, no efficient idea yet, but I think it's not necessary for the scope of that PR.

2025-02-03 16:14 UTC, fstoe commented on src/containers/ManifestListItem.js
> +    error: manifest.error || !manifesto,
thanks for spotting.

2025-02-04 08:16 UTC, lutzhelm commented on src/containers/ManifestListItem.js
> +    error: manifest.error || !manifesto,
Thanks, looks better now.

2025-02-04 08:16 UTC, lutzhelm approved these changes

2025-02-04 08:16 UTC, merged